-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQguSQsaXaSzU8lzgG7
qnVERNKjvZyIkgRYf9WciPbAvvCgCgYIKoZIzj0DAQehRANCAAT2BsnYovyf14Ia
dc/tffG3fBJI00GhdmpkVWciY27T0zKGCZaJYsbiJkrZrxW8tDbC5eRPxWzh63y6
YOvaaEeh
-----END PRIVATE KEY-----